"""fixed duplicate table

Revision ID: 302bb17058fa
Revises: 
Create Date: 2025-03-31 15:05:34.030374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '302bb17058fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('domain_1st', sa.String(), nullable=True),
    sa.Column('domain_2nd', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archival_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_archives_short_code'), 'visit_archives', ['short_code'], unique=False)
    op.create_index(op.f('ix_visit_archives_timestamp'), 'visit_archives', ['timestamp'], unique=False)
    op.add_column('short_links', sa.Column('auto_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('short_links', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('short_links', 'original_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_short_links_id', table_name='short_links')
    op.drop_column('short_links', 'country')
    op.drop_column('short_links', 'device_type')
    op.drop_column('short_links', 'deleted_at')
    op.drop_column('short_links', 'is_deleted')
    op.drop_column('short_links', 'domen2')
    op.drop_column('short_links', 'last_ip')
    op.drop_column('short_links', 'domen1')
    op.drop_column('short_links', 'referer')
    op.drop_column('short_links', 'visit_count')
    op.drop_index('ix_users_id', table_name='users')
    op.create_foreign_key(None, 'visits', 'short_links', ['short_code'], ['short_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.add_column('short_links', sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('short_links', sa.Column('referer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('short_links', sa.Column('domen1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('short_links', sa.Column('last_ip', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('short_links', sa.Column('domen2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('short_links', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('short_links', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('short_links', sa.Column('device_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('short_links', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_short_links_id', 'short_links', ['id'], unique=False)
    op.alter_column('short_links', 'original_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('short_links', 'short_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('short_links', 'auto_expires_at')
    op.drop_index(op.f('ix_visit_archives_timestamp'), table_name='visit_archives')
    op.drop_index(op.f('ix_visit_archives_short_code'), table_name='visit_archives')
    op.drop_table('visit_archives')
    # ### end Alembic commands ###
