"""change unique in archivelinks

Revision ID: 65b6acbd60dc
Revises: 7cc158277b83
Create Date: 2025-04-01 21:28:17.132041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b6acbd60dc'
down_revision: Union[str, None] = '7cc158277b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_short_links_archive_short_code', table_name='short_links_archive')
    op.create_index(op.f('ix_short_links_archive_short_code'), 'short_links_archive', ['short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_links_archive_short_code'), table_name='short_links_archive')
    op.create_index('ix_short_links_archive_short_code', 'short_links_archive', ['short_code'], unique=True)
    # ### end Alembic commands ###
