"""update tables visitor

Revision ID: 7cc158277b83
Revises: 302bb17058fa
Create Date: 2025-04-01 14:59:57.267583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc158277b83'
down_revision: Union[str, None] = '302bb17058fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_archives', sa.Column('owner', sa.Integer(), nullable=True))
    op.add_column('visits', sa.Column('owner', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'owner')
    op.drop_column('visit_archives', 'owner')
    # ### end Alembic commands ###
